## LANGUAGE
defaultContentLanguage: en

## ADVANCED
build:
  writeStats: true
enableRobotsTXT: true
imaging:
  quality: 75
markup:
  tableOfContents:
    ordered: true
pagination:
  pagerSize: 9
removePathAccents: true
disableHugoGeneratorInject: true
timeout: 100000
