imports:
  # Content
  - path: github.com/hugolify/hugolify-theme-casestudies
  - path: github.com/hugolify/hugolify-theme-expertises
  - path: github.com/hugolify/hugolify-theme-persons
  - path: github.com/hugolify/hugolify-theme-places
  - path: github.com/hugolify/hugolify-theme-products-tags
  - path: github.com/hugolify/hugolify-theme-products
  - path: github.com/hugolify/hugolify-theme-projects-tags
  - path: github.com/hugolify/hugolify-theme-projects-types
  - path: github.com/hugolify/hugolify-theme-projects
  - path: github.com/hugolify/hugolify-theme-posts-authors
  - path: github.com/hugolify/hugolify-theme-posts-categories
  - path: github.com/hugolify/hugolify-theme-posts-tags
  - path: github.com/hugolify/hugolify-theme-posts
  - path: github.com/hugolify/hugolify-theme-publications
  - path: github.com/hugolify/hugolify-theme-services-categories
  - path: github.com/hugolify/hugolify-theme-services

  # Core theme
  - path: github.com/hugolify/hugolify-theme

  # CMS
  - path: github.com/hugolify/hugolify-admin
