_merge: deep

admin:
  cms: cloudcannon
  media:
    public_folder: static/images/uploads

  # Groups
  collection_groups:
    - heading: Golbal
      collections:
        - casestudies
        - expertises
        - pages
        - persons
        - places
    - heading: Products
      collections:
        - products
        - products_tags
    - heading: Posts
      collections:
        - posts
        - posts_categories
        - posts_tags
    - heading: Projects
      collections:
        - projects
        - projects_tags
        - projects_types
    - heading: Publications
      collections:
        - publications
        - publications_categories
    - heading: Services
      collections:
        - services
        - services_categories

  # Collections
  collections:
    config:
      enable: false
    indexes:
      enable: false