_merge: deep

admin:
  cms: cloudcannon
  media:
    public_folder: static/images/uploads

  # Group
  collections_group:
    - heading: Products
      collections:
        - products
        - products_tags

  # Collections
  collections:
    config:
      enable: false
    indexes:
      enable: false