# Config
collections_config_override: false
paths:
  static: static
  uploads: static/images/uploads

# Snippets
_snippets_imports:
  hugo: true

# Collections
collections_config:
  products:
    _inputs:
      blocks:
        options:
          structures: _structures.blocks
        type: array
      date:
        instance_value: NOW
        name: Date
        options:
          required: true
        type: datetime
      title:
        comment: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        name: Page title
        options:
          required: true
        type: text
    comment: All products
    create:
      path: '[relative_base_path]/{year}/{slug}'
    disable_add: false
    disable_add_folder: true
    i18n: true
    name: Products
    path: content/products
    schemas:
      default:
        path: archetypes/products.md
    singular_name: Product


# Structures
_structures:
  blocks:
    style: modal
    values:
    - _inputs:
        background:
          name: With a background?
          options:
            required: false
          type: switch
        heading:
          name: Heading
          options:
            required: false
            subtype: object
          type: object
        heading.surtitle:
          name: Surtitle
          options:
            required: false
          type: text
        heading.text:
          name: Text
          options:
            allow_resize: false
            initial_height: 100
            required: false
          type: markdown
        heading.title:
          name: Title
          options:
            required: false
          type: text
      label: Title
      preview:
        icon: format_h2
        text:
        - key: title
        - Title
      value:
        background: 
        heading: 


