paths:
  uploads: /assets/images/uploads

collections_config:
  products:
    icon: shopping_cart
    name: products
    path: content/products
    create:
      path: '[relative_base_path]/{date|year}/{title|slugify}.md'
      default_front_matter:
        draft: true
    _inputs:
      draft:
        type: boolean
        label: Draft
      title:
        type: text
        label: Titre
      description:
        type: textarea
        label: Description
      image:
        type: object
        label: Image
        fields:
          src:
            type: image
            label: Image file
          alt:
            type: text
            label: Alternative text
  
  products_categories:
    path: content/products_categories
    name: Products categories
    icon: bookmark
    create:
      path: '[relative_base_path]/{title|slugify}/_index.md'
      default_front_matter:
        draft: true
    _inputs:
      draft:
        type: boolean
        label: Brouillon
      title:
        type: text
        label: Titre
      description:
        type: textarea
        label: Description

collection_groups:
  - heading: Products
    collections:
      - products
      - products_categories
    
_enabled_editors:
  - content