collections_config:
  products:
    icon: production_quantity_limits
    name: products
    path: content/products
    create:
      path: '[relative_base_path]/{date|year}/{title|slugify}.md'
    _inputs:
      draft:
        type: boolean
        label: Brouillon
      title:
        type: text
        label: Titre
      description:
        type: textarea
        label: Description
      image:
        type: object
        label: Image
        fields:
          src:
            type: image
            label: Fichier image
          alt:
            type: text
            label: Texte alternatif
  
  products_categories:
    path: content/products_categories
    name: Products categories
    icon: category
    create:
      path: '[relative_base_path]/{title|slugify}/_index.md'
    _inputs:
      draft:
        type: boolean
        label: Brouillon
      title:
        type: text
        label: Titre
      description:
        type: textarea
        label: Description


    
_enabled_editors:
  - content