


paths:
  static: static
  uploads: static/images/uploads


_snippets_imports:
  hugo: true


collections_config:
  pages:
    comment: All pages
    create:
      path: '[relative_base_path]/{title|slugify}/_index.md'
    disable_add: false
    disable_add_folder: true
    icon: description
    name: Pages
    path: content
    schemas:
      default:
        path: archetypes/pages.md
    singular_name: Page
  products:
    comment: All products
    create:
      path: '[relative_base_path]/{year}/{slug}'
    disable_add: false
    disable_add_folder: true
    name: Products
    path: content/products
    schemas:
      default:
        path: archetypes/products.md
    singular_name: Product



_structures:
  audio:
    values:
    - options: {}
      value:
        audio_mp3: null
        audio_ogg: null
        autoplay: null
        loop: null
        transcription: null
  author:
    values:
    - options: {}
      value:
        image_simple: null
        text: null
        title: null
  blocks:
    style: modal
    values:
    - label: Audio
      preview:
        text:
        - key: audio
        - Audio
      value:
        audio: null
        background: null
        heading: null
    - label: Alert
      preview:
        text:
        - key: alert
        - Alert
      value:
        background: null
        state: null
        text_markdown: null
    - label: Chart
      preview:
        text:
        - key: chart
        - Chart
      value:
        background: null
        chart: null
        grid: null
        heading: null
    - label: Comparison
      preview:
        text:
        - key: comparison
        - Comparison
      value:
        background: null
        column: null
        heading: null
        items: null
    - label: Call to action
      preview:
        text:
        - key: cta
        - Call to action
      value:
        background: null
        ctas: null
        heading: null
    - label: Datas
      preview:
        text:
        - key: datas
        - Datas
      value:
        background: null
        column: null
        heading: null
        items: null
        show_color: null
        show_gauge: null
    - label: Editorial
      preview:
        icon: vertical_split
        text:
        - key: editorial
        - Editorial
      value:
        background: null
        ctas: null
        direction: null
        image: null
        notes: null
        surtitle: null
        text_markdown: null
        title: null
    - label: Embed
      preview:
        text:
        - key: embed
        - Embed
      value:
        background: null
        embed: null
        heading: null
    - label: FAQ
      preview:
        text:
        - key: faq
        - FAQ
      value:
        background: null
        heading: null
        items: null
    - label: Figure
      preview:
        text:
        - key: figure
        - Figure
      value:
        background: null
        figure: null
        grid: null
        heading: null
        offset: null
    - label: Form
      preview:
        text:
        - key: form
        - Form
      value:
        background: null
        form_items: null
        grid: null
        heading: null
        name: null
        offset: null
        submit: null
    - label: Gallery
      preview:
        text:
        - key: gallery
        - Gallery
      value:
        background: null
        column: null
        gallery: null
        heading: null
    - label: Images
      preview:
        text:
        - key: images
        - Images
      value:
        background: null
        heading: null
        images: null
    - label: Informations
      preview:
        text:
        - key: informations
        - Informations
      value:
        background: null
        column: null
        heading: null
        items: null
    - label: Instagram
      preview:
        text:
        - key: instagram
        - Instagram
      value:
        background: null
        count: null
        ctas: null
        heading: null
        limit_simple: null
    - label: Latest items
      preview:
        text:
        - key: latest
        - Latest items
      value:
        background: null
        count: null
        heading: null
        layout: null
        section: null
        show_more: null
    - label: Logos
      preview:
        text:
        - key: logos
        - Logos
      value:
        background: null
        carousel: null
        heading: null
        items: null
        layout: null
    - label: Map
      preview:
        text:
        - key: map
        - Map
      value:
        background: null
        coordinates: null
        grid: null
        heading: null
        show_places: null
        zoom: null
    - label: Newsletter
      preview:
        text:
        - key: newsletter
        - Newsletter
      value:
        background: null
        heading: null
        newsletter_form: null
    - label: Paragraph
      preview:
        icon: subject
        text:
        - key: paragraph
        - Paragraph
      value:
        align: null
        background: null
        ctas: null
        grid: null
        notes: null
        offset: null
        surtitle: null
        text_markdown: null
        title: null
    - label: Pushes
      preview:
        text:
        - key: pushes
        - Pushes
      value:
        background: null
        carousel: null
        column_simple: null
        heading: null
        items: null
        layout: null
    - label: Quote
      preview:
        text:
        - key: quote
        - Quote
      value:
        author: null
        background: null
        quote: null
    - label: Search
      preview:
        text:
        - key: search
        - Search
      value:
        background: null
        heading: null
    - label: Selection <no value>
      preview:
        text:
        - key: selected
        - Selection <no value>
      value:
        background: null
        heading: null
        layout: null
        relation: null
        section-hidden: null
        show_more: null
    - label: Testimonials
      preview:
        text:
        - key: testimonials
        - Testimonials
      value:
        background: null
        carousel: null
        heading: null
        items: null
        layout: null
    - label: Timeline
      preview:
        text:
        - key: timeline
        - Timeline
      value:
        background: null
        heading: null
        items: null
    - label: Title
      preview:
        icon: format_h2
        text:
        - key: title
        - Title
      value:
        background: null
        heading: null
    - label: Video
      preview:
        text:
        - key: video
        - Video
      value:
        background: null
        grid: null
        heading: null
        video: null
  carousel:
    values:
    - options: {}
      value:
        carousel_params: null
        carousel_responsive: null
  chart:
    values:
    - options: {}
      value:
        chart_type: null
        title: null
  coordinates:
    values:
    - options: {}
      value:
        coordinates_lat: null
        coordinates_lng: null
  ctas:
    values:
    - options: {}
      value:
        is_blank: null
        lang: null
        text: null
        url: null
  figure:
    values:
    - options: {}
      value:
        credit: null
        image_alt: null
        image_src: null
        is_screenshot: null
        legend: null
  form_items:
    key: items
    values:
    - options: {}
      value:
        form_autocomplete: null
        form_options: null
        form_type: null
        form_value: null
        is_form_full: null
        is_required: null
        label: null
        name: null
        placeholder: null
  form_options:
    key: items
    values:
    - options: {}
      value:
        title: null
        value: null
  gallery:
    values:
    - options: {}
      value:
        credit: null
        image_alt: null
        image_src: null
        legend: null
  heading:
    values:
    - options: {}
      value:
        surtitle: null
        text_markdown: null
        title: null
  image:
    values:
    - options: {}
      value:
        credit: null
        image_alt: null
        image_src: null
  images:
    values:
    - options: {}
      value:
        credit: null
        image_alt: null
        image_src: null
        is_half: null
        legend: null
  newsletter_form:
    key: form
    values:
    - options: {}
      value:
        form_hiddens: null
        url: null
  notes:
    values:
    - options: {}
      value:
        text: null
  video:
    values:
    - options: {}
      value:
        autoplay: null
        controls: null
        legend: null
        loop: null
        poster: null
        transcription: null
        video_mp4: null
        video_webm: null



