# Config
collections_config_override: false
paths:
  static: static
  uploads: static/images/uploads

# Snippets
_snippets_imports:
  hugo: true

# Collections
collections_config:
  pages:
    _inputs:
      date:
        instance_value: NOW
        name: Date
        options:
          required: true
        type: datetime
      description:
        comment: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        name: Description
        options:
          required: false
        type: textarea
      draft:
        name: Draft
        options:
          required: false
        type: switch
      image:
        name: Images
        options:
          _inputs:
            alt:
              comment: For an image that conveys information (leave blank if decorative
                image)
              name: Text alternative
              options:
                required: false
              type: text
            credit:
              name: Credit
              options:
                allow_resize: false
                initial_height: 100
                required: false
              type: markdown
            src:
              comment: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
              name: Image
              options:
                max_file_size: "700000"
                required: false
              type: image
          required: false
          subtype: object
        type: object
      title:
        comment: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        name: Page title
        options:
          required: true
        type: text
    comment: All pages
    create:
      path: '[relative_base_path]/{title|slugify}/_index.md'
    disable_add: false
    disable_add_folder: true
    i18n: true
    icon: description
    name: Pages
    path: content
    schemas:
      default:
        path: archetypes/pages.md
    singular_name: Page
  products:
    _inputs:
      date:
        instance_value: NOW
        name: Date
        options:
          required: true
        type: datetime
      description:
        comment: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        name: Description
        options:
          required: false
        type: textarea
      draft:
        name: Draft
        options:
          required: false
        type: switch
      id:
        disabled: true
        instance_value: UUID
        name: ID
        type: text
      image:
        comment: Displayed in search results, and in SMS/Messages/Social networks
          preview
        name: Image principale
        options:
          _inputs:
            alt:
              comment: For an image that conveys information (leave blank if decorative
                image)
              name: Text alternative
              options:
                required: false
              type: text
            src:
              comment: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
              name: Image
              options:
                max_file_size: "700000"
                required: false
              type: image
          required: false
          subtype: object
        type: object
      isIndex:
        hidden: true
        name: is not index
        options:
          required: false
        type: switch
      offer:
        name: Offer
        options:
          _inputs:
            discount:
              comment: 'Amount of the reduction, e.g: 30%'
              name: Discount
              options:
                pattern: ^[0-9]*(%?)$
                pattern_message: Value only (without currency)
                required: false
              type: text
            hide_price:
              name: Hide price
              options:
                required: false
              type: switch
            price:
              comment: 'e.g: 300000 (for 300 000 â‚¬)'
              name: Price
              options:
                required: false
              type: number
            text:
              name: Text
              options:
                required: false
              type: text
          required: false
          subtype: object
        type: object
      title:
        comment: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        name: Page title
        options:
          required: true
        type: text
    comment: All products
    create:
      path: '[relative_base_path]/{{year}}/{{slug}}'
    disable_add: false
    disable_add_folder: true
    i18n: true
    name: Products
    path: content/products
    schemas:
      default:
        path: archetypes/products.md
    singular_name: Product


