collections_config_override: false
paths:
  static: static
  uploads: assets/images/uploads
timezone: Etc/UTC

# Collections
collections_config:

  products:
    create:
      path: '[relative_base_path]/{title|slugify}.md'
    disable_add_folder: true
    icon: shopping_cart
    name: products
    path: content/products
    base_url: /products
    _inputs:
      - draft
      - title
      - description
      - image
  
  products_categories:
    create:
      path: '[relative_base_path]/{title|slugify}/_index.md'
    disable_add_folder: true
    icon: bookmark
    name: Products categories
    path: content/products_categories
    _inputs:
      - draft
      - title
      - description

# Display
collection_groups:
  - heading: Products
    collections:
      - products
      - products_categories

# Fields
_inputs:
  draft:
    type: boolean
    label: Draft
  title:
    type: text
    label: Titre
  description:
    type: textarea
    label: Description
  image:
    type: object
    label: Image
    fields:
      src:
        type: image
        label: Image file
      alt:
        type: text
        label: Alternative text