paths:
  uploads: /assets/images/uploads

collections_config:
  products:
    icon: shopping_cart
    name: products
    path: content/products
    base_url: /products
    disable_add_folder: true
    create:
      path: '[relative_base_path]/{title|slugify}.md'
    _schema:
      - draft
      - title
      - description
      - image
  
  products_categories:
    path: content/products_categories
    name: Products categories
    icon: bookmark
    disable_add_folder: true
    create:
      path: '[relative_base_path]/{title|slugify}/_index.md'
    _schema:
      - draft
      - title
      - description

collection_groups:
  - heading: Products
    collections:
      - products
      - products_categories
    
_enabled_editors:
  - content

_inputs:
  draft:
    type: boolean
    label: Draft
  title:
    type: text
    label: Titre
  description:
    type: textarea
    label: Description
  image:
    type: object
    label: Image
    fields:
      src:
        type: image
        label: Image file
      alt:
        type: text
        label: Alternative text