# Config
collections_config_override: false
paths:
  static: static
  uploads: assets/images/uploads

# Snippets
_snippets_imports:
  hugo: true

# Collections
collections_config:
  products:
    _inputs:
      body:
        i18n: true
        label: Body
        name: body
        required: false
        type: markdown
      date:
        default: '{{now}}'
        i18n: duplicate
        label: Date
        name: date
        required: true
        type: datetime
      description:
        hint: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        i18n: true
        label: Description
        name: description
        required: false
        type: text
      draft:
        default: true
        i18n: true
        label: Draft
        name: draft
        required: false
        type: switch
      image:
        collapsed: true
        i18n: true
        label: Image
        name: image
        options:
          _inputs:
            credit:
              buttons:
              - link
              editor_components: []
              i18n: true
              label: Credit
              minimal: true
              modes:
              - rich_text
              name: credit
              required: false
              type: markdown
            image_alt:
              hint: For an image that conveys information (leave blank if decorative
                image)
              i18n: true
              label: Text alternative
              name: alt
              required: false
              type: string
            image_src:
              choose_url: false
              hint: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
              i18n: true
              label: Image
              media_folder: /assets/images/uploads
              media_library:
                config:
                  max_file_size: "700000"
              name: src
              public_folder: /images/uploads
              required: false
              type: image
        required: false
        type: object
      title_page:
        hint: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        i18n: true
        label: Page title
        name: title
        required: true
        type: string
    schemas:
      default:
        path: archetypes/products.md


