# Config
collections_config_override: false
paths:
  static: static
  uploads: static/images/uploads

# Snippets
_snippets_imports:
  hugo: true

# Collections
collections_config:
  pages:
    _inputs:
      date:
        default: '{{now}}'
        i18n: duplicate
        name: Date
        required: true
        type: datetime
        widget_name: date
      description:
        comment: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        i18n: true
        name: Description
        required: false
        type: text
        widget_name: description
      draft:
        default: true
        i18n: true
        name: Draft
        required: false
        type: switch
        widget_name: draft
      image:
        collapsed: true
        i18n: true
        name: Image
        options:
          _inputs:
            alt:
              comment: For an image that conveys information (leave blank if decorative
                image)
              i18n: true
              name: Text alternative
              required: false
              type: text
              widget_name: alt
            credit:
              buttons:
              - link
              editor_components: []
              i18n: true
              minimal: true
              modes:
              - rich_text
              name: Credit
              required: false
              type: markdown
              widget_name: credit
            src:
              choose_url: false
              comment: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
              i18n: true
              media_folder: /assets/images/uploads
              media_library:
                config:
                  max_file_size: "700000"
              name: Image
              public_folder: static/images/uploads
              required: false
              type: image
              widget_name: src
          subtype: object
        required: false
        type: object
        widget_name: image
      title:
        comment: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        i18n: true
        name: Page title
        required: true
        type: text
        widget_name: title
    comment: All pages
    create:
      path: '[relative_base_path]/{title|slugify}/_index.md'
    disable_add: false
    disable_add_folder: true
    i18n: true
    icon: description
    name: Pages
    path: content
    schemas:
      default:
        path: archetypes/pages.md
    singular_name: Page
  products:
    _inputs:
      date:
        default: '{{now}}'
        i18n: duplicate
        name: Date
        required: true
        type: datetime
        widget_name: date
      description:
        comment: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        i18n: true
        name: Description
        required: false
        type: text
        widget_name: description
      draft:
        default: true
        i18n: true
        name: Draft
        required: false
        type: switch
        widget_name: draft
      id:
        i18n: duplicate
        name: Id
        type: uuid
        widget_name: id
      image:
        collapsed: true
        comment: Displayed in search results, and in SMS/Messages/Social networks
          preview
        i18n: true
        name: Image principale
        options:
          _inputs:
            alt:
              comment: For an image that conveys information (leave blank if decorative
                image)
              i18n: true
              name: Text alternative
              required: false
              type: text
              widget_name: alt
            src:
              choose_url: false
              comment: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
              i18n: true
              media_folder: /assets/images/uploads
              media_library:
                config:
                  max_file_size: "700000"
              name: Image
              public_folder: static/images/uploads
              required: false
              type: image
              widget_name: src
          subtype: object
        required: false
        type: object
        widget_name: image
      images:
        collapsed: true
        i18n: true
        name: Images
        options:
          _inputs:
            alt:
              comment: For an image that conveys information (leave blank if decorative
                image)
              i18n: true
              name: Text alternative
              required: false
              type: text
              widget_name: alt
            credit:
              buttons:
              - link
              editor_components: []
              i18n: true
              minimal: true
              modes:
              - rich_text
              name: Credit
              required: false
              type: markdown
              widget_name: credit
            half:
              i18n: duplicate
              name: Half size?
              required: false
              type: switch
              widget_name: half
            legend:
              i18n: true
              name: Legend
              required: false
              type: text
              widget_name: legend
            src:
              choose_url: false
              comment: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
              i18n: true
              media_folder: /assets/images/uploads
              media_library:
                config:
                  max_file_size: "700000"
              name: Image
              public_folder: static/images/uploads
              required: false
              type: image
              widget_name: src
          subtype: object
        required: false
        type: array
        widget_name: images
      isIndex:
        default: false
        i18n: false
        name: is not index
        required: false
        type: hidden
        widget_name: isIndex
      offer:
        collapsed: false
        i18n: true
        name: Offer
        options:
          _inputs:
            discount:
              comment: 'Amount of the reduction, e.g: 30%'
              i18n: duplicate
              name: Discount
              pattern:
              - ^[0-9]*(%?)$
              - Value only (without currency)
              required: false
              type: text
              widget_name: discount
            hide_price:
              i18n: duplicate
              name: Hide price
              required: false
              type: switch
              widget_name: hide_price
            price:
              comment: 'e.g: 300000 (for 300 000 â‚¬)'
              i18n: duplicate
              name: Price
              required: false
              type: number
              widget_name: price
            text:
              i18n: true
              name: Text
              required: false
              type: text
              widget_name: text
          subtype: object
        required: false
        type: object
        widget_name: offer
      slug:
        comment: Leave empty to automate with the title. **Be careful to SEO impact.**
        i18n: true
        name: Slug
        pattern:
        - ^(|[a-z0-9-]&#43;)$
        - Contain only lowercase letters, numbers, and hyphens, with no spaces, accents,
          or special characters
        required: false
        type: text
        widget_name: slug
      title:
        comment: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        i18n: true
        name: Page title
        required: true
        type: text
        widget_name: title
    comment: All products
    create:
      path: '[relative_base_path]/{{year}}/{{slug}}'
    disable_add: false
    disable_add_folder: true
    i18n: true
    name: Products
    path: content/products
    schemas:
      default:
        path: archetypes/products.md
    singular_name: Product


