# Config
collections_config_override: false
paths:
  static: static
  uploads: static/images/uploads

# Snippets
_snippets_imports:
  hugo: true

# Collections
collections_config:
  pages:
    _inputs:
      date:
        default: '{{now}}'
        i18n: duplicate
        label: Date
        name: date
        required: true
        type: datetime
      description:
        hint: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        i18n: true
        label: Description
        name: description
        required: false
        type: text
      draft:
        default: true
        i18n: true
        label: Draft
        name: draft
        required: false
        type: switch
      image:
        collapsed: true
        i18n: true
        label: Image
        name: image
        options:
          _inputs:
            alt:
              hint: For an image that conveys information (leave blank if decorative
                image)
              i18n: true
              label: Text alternative
              name: alt
              required: false
              type: text
            credit:
              buttons:
              - link
              editor_components: []
              i18n: true
              label: Credit
              minimal: true
              modes:
              - rich_text
              name: credit
              required: false
              type: markdown
            src:
              choose_url: false
              hint: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
              i18n: true
              label: Image
              media_folder: /assets/images/uploads
              media_library:
                config:
                  max_file_size: "700000"
              name: src
              public_folder: static/images/uploads
              required: false
              type: image
          subtype: object
        required: false
        type: object
      title:
        hint: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        i18n: true
        label: Page title
        name: title
        required: true
        type: text
    create:
      path: '[relative_base_path]/{title|slugify}/_index.md'
    description: All pages
    disable_add: false
    disable_add_folder: true
    i18n: true
    icon: description
    name: Pages
    path: content
    schemas:
      default:
        path: archetypes/pages.md
    singular_name: Page
  products:
    _inputs:
      date:
        default: '{{now}}'
        i18n: duplicate
        label: Date
        name: date
        required: true
        type: datetime
      description:
        hint: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        i18n: true
        label: Description
        name: description
        required: false
        type: text
      draft:
        default: true
        i18n: true
        label: Draft
        name: draft
        required: false
        type: switch
      id:
        i18n: duplicate
        label: Id
        name: id
        type: uuid
      image:
        collapsed: true
        hint: Displayed in search results, and in SMS/Messages/Social networks preview
        i18n: true
        label: Image principale
        name: image
        options:
          _inputs:
            alt:
              hint: For an image that conveys information (leave blank if decorative
                image)
              i18n: true
              label: Text alternative
              name: alt
              required: false
              type: text
            src:
              choose_url: false
              hint: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
              i18n: true
              label: Image
              media_folder: /assets/images/uploads
              media_library:
                config:
                  max_file_size: "700000"
              name: src
              public_folder: static/images/uploads
              required: false
              type: image
          subtype: object
        required: false
        type: object
      images:
        collapsed: true
        i18n: true
        label: Images
        name: images
        options:
          _inputs:
            alt:
              hint: For an image that conveys information (leave blank if decorative
                image)
              i18n: true
              label: Text alternative
              name: alt
              required: false
              type: text
            credit:
              buttons:
              - link
              editor_components: []
              i18n: true
              label: Credit
              minimal: true
              modes:
              - rich_text
              name: credit
              required: false
              type: markdown
            half:
              i18n: duplicate
              label: Half size?
              name: half
              required: false
              type: switch
            legend:
              i18n: true
              label: Legend
              name: legend
              required: false
              type: text
            src:
              choose_url: false
              hint: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
              i18n: true
              label: Image
              media_folder: /assets/images/uploads
              media_library:
                config:
                  max_file_size: "700000"
              name: src
              public_folder: static/images/uploads
              required: false
              type: image
          subtype: object
        required: false
        type: list
      isIndex:
        default: false
        i18n: false
        label: is not index
        name: isIndex
        required: false
        type: hidden
      offer:
        collapsed: false
        i18n: true
        label: Offer
        name: offer
        options:
          _inputs:
            discount:
              hint: 'Amount of the reduction, e.g: 30%'
              i18n: duplicate
              label: Discount
              name: discount
              pattern:
              - ^[0-9]*(%?)$
              - Value only (without currency)
              required: false
              type: text
            hide_price:
              i18n: duplicate
              label: Hide price
              name: hide_price
              required: false
              type: switch
            price:
              hint: 'e.g: 300000 (for 300 000 â‚¬)'
              i18n: duplicate
              label: Price
              name: price
              required: false
              type: number
            text:
              i18n: true
              label: Text
              name: text
              required: false
              type: text
          subtype: object
        required: false
        type: object
      slug:
        hint: Leave empty to automate with the title. **Be careful to SEO impact.**
        i18n: true
        label: Slug
        name: slug
        pattern:
        - ^(|[a-z0-9-]&#43;)$
        - Contain only lowercase letters, numbers, and hyphens, with no spaces, accents,
          or special characters
        required: false
        type: text
      title:
        hint: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        i18n: true
        label: Page title
        name: title
        required: true
        type: text
    create:
      path: '[relative_base_path]/{{year}}/{{slug}}'
    description: All products
    disable_add: false
    disable_add_folder: true
    i18n: true
    name: Products
    path: content/products
    schemas:
      default:
        path: archetypes/products.md
    singular_name: Product


