


paths:
  static: static
  uploads: static/images/uploads


_snippets_imports:
  hugo: true


collections_config:
  pages:
    comment: All pages
    create:
      path: '[relative_base_path]/{title|slugify}/_index.md'
    disable_add: false
    disable_add_folder: true
    icon: description
    name: Pages
    path: content
    schemas:
      default:
        path: archetypes/pages.md
    singular_name: Page
  products:
    comment: All products
    create:
      path: '[relative_base_path]/{year}/{slug}'
    disable_add: false
    disable_add_folder: true
    name: Products
    path: content/products
    schemas:
      default:
        path: archetypes/products.md
    singular_name: Product



_inputs:
  align:
    name: Alignment
    options:
      required: false
      value_key: value
      values:
      - name: Start
        value: start
      - name: Center
        value: center
      - name: End
        value: end
    type: select
  alt:
    comment: For an image that conveys information (leave blank if decorative image)
    name: Text alternative
    options:
      required: false
    type: text
  autocomplete:
    name: Autocomplete
    options:
      required: false
      value_key: value
      values:
      - name: Email
        value: email
      - name: Tel
        value: tel
      - name: Honorific prefix
        value: honorific-prefix
      - name: Given name
        value: given-name
      - name: Family name
        value: family-name
      - name: Name
        value: name
      - name: Street address
        value: street-address
      - name: Address level1
        value: address-level1
      - name: Address level2
        value: address-level2
      - name: Postal code
        value: postal-code
      - name: Country name
        value: country-name
      - name: Organization
        value: organization
    type: select
  autoplay:
    name: Autoplay
    options:
      required: false
    type: switch
  background:
    name: With a background?
    options:
      required: false
    type: switch
  blank:
    name: Is blank?
    options:
      required: false
    type: switch
  chart_type:
    name: Chart type
    options:
      required: false
      value_key: value
      values:
      - name: Bar
        value: bar
      - name: Pie
        value: pie
      - name: Line
        value: line
      - name: Polar area
        value: polarArea
      - name: Radar
        value: radar
    type: select
  column:
    name: Column
    options:
      max: 2
      min: 1
      required: false
      step: 1
    type: range
  controls:
    name: Controls
    options:
      required: false
    type: switch
  count:
    comment: Items to display
    name: Count
    options:
      max: 10
      min: 1
      required: false
      step: 1
    type: range
  credit:
    name: Credit
    options:
      allow_resize: false
      initial_height: 100
      required: false
    type: markdown
  direction:
    name: Direction
    options:
      required: false
      value_key: value
      values:
      - name: Ltr
        value: ltr
      - name: Rtl
        value: rtl
    type: select
  embed:
    name: Embed
    options:
      required: false
    type: textarea
  full:
    name: Full width field?
    options:
      required: false
    type: switch
  grid:
    name: Grid
    options:
      required: true
      value_key: value
      values:
      - name: Small
        value: small
      - name: Medium
        value: medium
      - name: Large
        value: large
      - name: Container
        value: container
      - name: Full
        value: full
    type: select
  half:
    name: Half size?
    options:
      required: false
    type: switch
  hiddens:
    fields:
    - name
    - value
    name: nolabel
    options:
      required: false
      structures: _structures.hiddens
    real_fields:
    - name
    - value
    type: array
  image:
    fields:
    - image_src
    - image_alt
    - is_logo
    name: Images
    options:
      required: false
      structures: _structures.image
      subtype: object
    real_fields:
    - image_src
    - image_alt
    - is_logo
    type: object
  label:
    name: Label
    options:
      required: false
    type: text
  lang:
    comment: Enter code lang (e.g. fr) if different of the current page language
    name: Language
    options:
      required: false
    type: text
  lat:
    name: Latitude
    options:
      required: false
    type: number
  legend:
    name: Legend
    options:
      required: false
    type: text
  limit_simple:
    name: Limit
    options:
      max: 10
      min: 1
      required: false
      step: 1
    type: range
  lng:
    name: Longitude
    options:
      required: false
    type: number
  loop:
    name: Loop
    options:
      required: false
    type: switch
  mp3:
    comment: MP3 audio file
    name: MP3
    options:
      accepts_mime_types:
      - audio/mpeg
      max_file_size: "700000"
      required: false
    type: file
  mp4:
    comment: MP4 video file
    name: MP4
    options:
      accepts_mime_types:
      - video/mp4
      max_file_size: "5000000"
      required: false
    type: file
  name:
    name: Name
    options:
      required: false
    type: text
  offset:
    name: Offset
    options:
      required: false
      value_key: value
      values:
      - name: Start
        value: start
      - name: Center
        value: center
      - name: End
        value: end
    type: select
  ogg:
    comment: OGG audio file
    name: OGG
    options:
      accepts_mime_types:
      - audio/ogg
      max_file_size: "700000"
      required: false
    type: file
  params:
    fields:
    - carousel_focus
    - carousel_autoplay
    - carousel_arrows
    - carousel_pagination
    - carousel_type
    - carousel_perpage
    - carousel_padding
    - carousel_gap
    name: Params
    options:
      required: false
      structures: _structures.params
      subtype: object
    real_fields:
    - carousel_focus
    - carousel_autoplay
    - carousel_arrows
    - carousel_pagination
    - carousel_type
    - carousel_perpage
    - carousel_padding
    - carousel_gap
    type: object
  placeholder:
    name: Placeholder
    options:
      required: false
    type: text
  poster:
    comment: Placehoster image for video
    name: Poster
    options:
      accepts_mime_types:
      - image/gif
      - image/jpeg
      - image/png
      - image/webp
      - image/svg+xml
      max_file_size: "700000"
      paths:
        static: static/images/uploads
        uploads: /assets/images/uploads
      required: false
    type: image
  quote:
    name: Quote
    options:
      allow_resize: false
      initial_height: 100
      required: false
    type: markdown
  required:
    name: Required
    options:
      required: false
    type: switch
  responsive:
    fields:
    - breakpoints
    - carousel_params
    name: Responsive
    options:
      required: false
      structures: _structures.responsive
    real_fields:
    - breakpoints
    - carousel_params
    type: array
  screenshot:
    name: nolabel
    options:
      required: false
    type: switch
  section:
    name: Section
    options:
      required: false
      value_key: value
      values:
      - name: Pages
        value: pages
      - name: Products
        value: products
    type: select
  show_more:
    name: Show more?
    options:
      required: false
    type: switch
  show_places:
    comment: Only if you have places already saved (this will disable the marker below)
    name: Show all registered places?
    options:
      required: false
    type: switch
  src:
    comment: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
    name: Image
    options:
      accepts_mime_types:
      - image/gif
      - image/jpeg
      - image/png
      - image/webp
      - image/svg+xml
      max_file_size: "700000"
      paths:
        static: static/images/uploads
        uploads: /assets/images/uploads
      required: false
    type: image
  state:
    name: State
    options:
      required: true
      value_key: value
      values:
      - name: Danger
        value: danger
      - name: Dark
        value: dark
      - name: Info
        value: info
      - name: Light
        value: light
      - name: Primary
        value: primary
      - name: Secondary
        value: secondary
      - name: Success
        value: success
      - name: Warning
        value: warning
    type: select
  submit:
    name: Send button text
    options:
      required: false
    type: text
  surtitle:
    name: Surtitle
    options:
      required: false
    type: text
  text:
    name: Text
    options:
      required: false
    type: text
  text_markdown:
    name: Text
    options:
      allow_resize: false
      initial_height: 100
      required: false
    type: markdown
  title:
    name: Title
    options:
      required: false
    type: text
  transcription:
    name: Transcription
    options:
      required: false
    type: textarea
  type:
    name: Type
    options:
      required: true
      value_key: value
      values:
      - name: Email
        value: email
      - name: Checkbox
        value: checkbox
      - name: Radio
        value: radio
      - name: Select
        value: select
      - name: Tel
        value: tel
      - name: Text
        value: text
      - name: Textarea
        value: textarea
    type: select
  url:
    name: URL
    options:
      required: false
    type: text
  value:
    comment: Only for checkbox and radio fields
    name: Value
    options:
      required: false
    type: text
  webm:
    comment: WEBM video file
    name: WEBM
    options:
      accepts_mime_types:
      - video/webm
      max_file_size: "5000000"
      required: false
    type: file
  zoom:
    name: Zoom
    options:
      max: 20
      min: 1
      required: false
      step: 1
    type: number
,