# Config
collections_config_override: false
paths:
  static: static
  uploads: static/images/uploads

# Snippets
_snippets_imports:
  hugo: true

# Collections
collections_config:
  products:
    _inputs:
      blocks:
        options:
          structures: _structures.blocks
        type: array
      date:
        instance_value: NOW
        name: Date
        options:
          required: true
        type: datetime
      title:
        comment: Displayed in tabs, search results, and in SMS/Messages/Social networks
          preview
        name: Page title
        options:
          required: true
        type: text
    comment: All products
    create:
      path: '[relative_base_path]/{year}/{slug}'
    disable_add: false
    disable_add_folder: true
    i18n: true
    name: Products
    path: content/products
    schemas:
      default:
        path: archetypes/products.md
    singular_name: Product


# Structures
_structures:
  blocks:
    style: modal
    values:
    - _inputs:
        background:
          name: With a background?
          options:
            required: false
          type: switch
        cta:
          name: CTAs
          options:
            _inputs:
              blank:
                name: Is blank?
                options:
                  required: false
                type: switch
              lang:
                comment: Enter code lang (e.g. fr) if different of the current page
                  language
                name: Language
                options:
                  required: false
                type: text
              text:
                name: Text
                options:
                  required: false
                type: text
              url:
                name: URL
                options:
                  required: false
                type: text
            'max_items:': 2
            required: false
          singular_name: CTA
          type: array
        direction:
          name: Direction
          options:
            required: false
            value_key: value
            values:
            - name: Ltr
              value: ltr
            - name: Rtl
              value: rtl
          type: select
        image:
          name: Images
          options:
            _inputs:
              alt:
                comment: For an image that conveys information (leave blank if decorative
                  image)
                name: Text alternative
                options:
                  required: false
                type: text
              credit:
                name: Credit
                options:
                  allow_resize: false
                  initial_height: 100
                  required: false
                type: markdown
              src:
                comment: 'Resize and compress image before sending : https://bulkresizephotos.com/fr?quality=90&type=width&width=1600'
                name: Image
                options:
                  max_file_size: "700000"
                  required: false
                type: image
            required: false
            subtype: object
          type: object
        notes:
          comment: To link a word in the text to a note, suffix it with "[*]". Notes
            and "[\\*]" are linked by their order.
          name: Notes
          options:
            _inputs:
              text:
                name: Text
                options:
                  required: false
                type: text
            required: false
          singular_name: Note
          type: array
        surtitle:
          name: Surtitle
          options:
            required: false
          type: text
        text:
          name: Text
          options:
            allow_resize: false
            initial_height: 100
            required: false
          type: markdown
        title:
          name: Title
          options:
            required: false
          type: text
      label: Editorial
      preview:
        icon: vertical_split
        text:
        - key: editorial
        - Editorial
      value:
        background: 
        ctas: 
        direction: 
        image: 
        notes: 
        surtitle: 
        text_markdown: 
        title: 
    - _inputs:
        background:
          name: With a background?
          options:
            required: false
          type: switch
        heading:
          name: Heading
          options:
            _inputs:
              surtitle:
                name: Surtitle
                options:
                  required: false
                type: text
              text:
                name: Text
                options:
                  allow_resize: false
                  initial_height: 100
                  required: false
                type: markdown
              title:
                name: Title
                options:
                  required: false
                type: text
            required: false
            subtype: object
          type: object
      label: Title
      preview:
        icon: format_h2
        text:
        - key: title
        - Title
      value:
        background: 
        heading: 


