# Config
paths:
  static: static
  uploads: static/images/uploads

# Snippets
_snippets_imports:
  hugo: true

# Collections
collections_config:
  pages:
    _inputs:
      blocks:
        options:
          structures: _structures.blocks
        type: array
      draft:
        name: Draft
        options:
          required: false
        type: switch
    comment: All pages
    create:
      path: '[relative_base_path]/{title|slugify}/_index.md'
    disable_add: false
    disable_add_folder: true
    icon: description
    name: Pages
    path: content
    schemas:
      default:
        path: archetypes/pages.md
    singular_name: Page


# Structures
_structures:
  blocks:
    style: modal
    values:
    - _inputs:
        align:
          name: Alignment
          options:
            required: false
            value_key: value
            values:
            - name: Start
              value: start
            - name: Center
              value: center
            - name: End
              value: end
          type: select
        background:
          name: With a background?
          options:
            required: false
          type: switch
        cta:
          fields:
          - text
          - url
          - lang
          - is_blank
          name: CTAs
          options:
            max_items: 2
            required: false
            structures: _structures.cta
          singular_name: CTA
          type: array
        grid:
          name: Grid
          options:
            required: true
            value_key: value
            values:
            - name: Small
              value: small
            - name: Medium
              value: medium
            - name: Large
              value: large
            - name: Container
              value: container
            - name: Full
              value: full
          type: select
        notes:
          comment: To link a word in the text to a note, suffix it with "[*]". Notes
            and "[*]" are linked by their order.
          fields:
          - text
          name: Notes
          options:
            required: false
            structures: _structures.notes
          singular_name: Note
          type: array
        offset:
          name: Offset
          options:
            required: false
            value_key: value
            values:
            - name: Start
              value: start
            - name: Center
              value: center
            - name: End
              value: end
          type: select
        surtitle:
          name: Surtitle
          options:
            required: false
          type: text
        text:
          name: Text
          options:
            allow_resize: false
            initial_height: 100
            required: false
          type: markdown
        title:
          name: Title
          options:
            required: false
          type: text
      label: Paragraph
      preview:
        icon: subject
        text:
        - key: paragraph
        - Paragraph
      value:
        align: null
        background: null
        ctas: null
        grid: null
        notes: null
        offset: null
        surtitle: null
        text_markdown: null
        title: null
  notes:
    values:
    - options:
        _inputs:
          text:
            name: Text
            options:
              required: false
            type: text
      value:
        text: null


