_schema: _schema
source: /
paths:
  uploads: static/images/uploads
  static: static
collections_config:
  products:
    path: content/products
    glob:
      - '!_index.md'
    name: Products
    singular_name:
    icon: shopping_cart
    url:
    include_developer_files:
    documentation:
    description: ''
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
      - visual
      - content
      - data
    _inputs:
      draft:
        type: switch
        label: Draft
        cascade: true
      title:
        type: text
        label: Page title
        cascade: true
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
_inputs:
  draft:
    type: switch
    label: Draft
    cascade: true
  title:
    type: text
    label: Title
    cascade: true
  description:
    type: textarea
    label: Description
    cascade: true
  src:
    type: image
    options:
      paths:
      mime_type:
      accepts_mime_types:
        - image/svg+xml
        - image/jpeg
        - image/png
      empty_type:
      resize_style:
      width: 1
      height: 1
      expandable:
      allowed_sources:
      prevent_resize_existing_files:
      sizes:
    label: Image
    cascade: true
  alt:
    type: text
    label: Alternative text
    cascade: true
_structures:
  image:
    style: modal
    id_key:
    values:
      - id:
        default:
        icon:
        image:
        label:
        picker_preview:
        preview:
        tags:
        groups:
          - heading: Image
            comment: ''
            documentation:
            collapsed:
            inputs:
              - src
              - alt
        place_groups_below:
        tabbed:
        value:
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
editor:
  default_path:
timezone: Europe/Paris
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
