[build]
  command = "hugo --noChmod --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.109.0"
  GO_VERSION = "1.19.4"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_ENV = "staging"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
