---
label: Author
hide_body: true
fields:
- type: boolean
  name: index
  label: index
- type: text
  name: title
  label: title
- type: textarea
  name: description
  label: description
- type: text
  name: email
  label: email
- type: text
  name: twitter
  label: twitter
